title: "EpicHugge"
description: "Your short description here."
baseurl: ""
url: ""
email: "your-email@example.com"

twitter_username: "jekyllrb"
github_username: "jekyll"

theme:

plugins:
  - jekyll-feed